version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "443:443"
    volumes:
      - /home/hippo3233/eNurse/certificate/:/etc/nginx/ssl:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      # - gpt_chat
      # - e-nurse_chat
      - php
      - mysql
      - phpmyadmin
    networks:
      - hospital_net

    restart: "no"

  php:
    build: ./php
    container_name: php_server
    ports:
      - "8080:80"
    volumes:
      - ./apache:/var/www/html
    env_file:
      - .env
    networks:
      - hospital_net

    restart: "no"

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - hospital_net
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: "no"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql # indicate the mysql service name (for PHPMyAdmin to connect)
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - hospital_net
# ports:
#   - "8082:80"


volumes:
  mysql_data:


networks:
  hospital_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.50.0.0/16
  